 // DO NOT CHANGE - THIS IS GENERATED BY BUILD.PY
document.querySelector("#app").innerHTML = `
    <h1 class="title">Changelog</h1>
    <p>The following is a list of changes made to the website, generated by the build script using git commits.</p><br>
<p>Fix rendering on changelog
 - Latest commit</p><button class='time-btn'>2024-04-21 22:18:07</button><hr><p>Cleanup & add change log page (no tracking)
</p><button class='time-btn'>2024-04-21 22:07:17</button><hr><p>update styles & add more projects
</p><button class='time-btn'>2024-04-15 01:37:26</button><hr><p>Add tracking for '/projects/project'
</p><button class='time-btn'>2024-04-07 15:28:52</button><hr><p>Fix build (x2)
</p><button class='time-btn'>2024-04-07 00:54:40</button><hr><p>Fix build
</p><button class='time-btn'>2024-04-07 00:52:30</button><hr><p>Add dynmic project page
</p><button class='time-btn'>2024-04-07 00:46:30</button><hr><p>Correct protocol for api</p><button class='time-btn'>2024-04-02 23:54:53</button><hr><p>Update lib.rs</p><button class='time-btn'>2024-04-02 18:02:24</button><hr><p>Change Icon
</p><button class='time-btn'>2024-04-02 17:37:06</button><hr><p>Change icon
</p><button class='time-btn'>2024-04-02 17:36:57</button><hr><p>temp api fix
</p><button class='time-btn'>2024-04-02 17:21:13</button><hr><p>Update API url
</p><button class='time-btn'>2024-04-02 16:00:34</button><hr><p>Update
</p><button class='time-btn'>2024-04-02 15:02:26</button><hr><p>add 404
</p><button class='time-btn'>2024-04-01 13:54:35</button><hr><p>add projects
</p><button class='time-btn'>2024-04-01 12:34:55</button><hr><p>first commit
</p><button class='time-btn'>2024-03-30 15:32:37</button><hr> `; 