 // DO NOT CHANGE - THIS IS GENERATED BY BUILD.PY
document.querySelector("#app").innerHTML = `
    <h1 class="title">Changelog</h1>
    <p>The following is a list of changes made to the website, generated by the build script using git commits.</p><br>

<p>update styles & add more projects
 - Latest commit</p><hr><p>Add tracking for '/projects/project'
</p><hr><p>Fix build (x2)
</p><hr><p>Fix build
</p><hr><p>Add dynmic project page
</p><hr><p>Correct protocol for api</p><hr><p>Update lib.rs</p><hr><p>Change Icon
</p><hr><p>Change icon
</p><hr><p>temp api fix
</p><hr><p>Update API url
</p><hr><p>Update
</p><hr><p>add 404
</p><hr><p>add projects
</p><hr><p>first commit
</p><hr> `; 