// Do not edit this file. Edit projects.toml instead.

const PROJECTS = [
    `<td>
        <a href="project_website.html">
            <div class="project">
                <h2 class="project-title"><b>Website</b></h2>
                <p>This website.</p><a class="badge open-source" href="https://github.com/harvey298/2024-website" target="_blank">Open Source</a> <div class="badge alpha">Alpha</div> <div class="badge active">Active</div> <div class="badge js">Language: js</div><div class="badge html">Language: html</div><div class="badge css">Language: css</div> <div class="badge framework">Framework: Vite</div>
            </div>
        </a></td>`,`<td>
        <a href="project_olympus.html">
            <div class="project">
                <h2 class="project-title"><b>Olympus</b></h2>
                <p>Machine Learning powered stock trading algorithm.</p><div class="badge closed-source">Closed Source</div> <div class="badge stable">Stable</div> <div class="badge maintenance">In Maintenance</div> <div class="badge rust">Language: rust</div> <div class="badge framework">Tool: pytorch</div>
            </div>
        </a></td>`,`<td>
        <a href="project_avaritia.html">
            <div class="project">
                <h2 class="project-title"><b>Avaritia</b></h2>
                <p>Cryptocurrency trading bot.</p><div class="badge closed-source">Closed Source</div> <div class="badge stable">Stable</div> <div class="badge active">Active</div> <div class="badge rust">Language: rust</div> 
            </div>
        </a></td>`,`<td>
        <a href="project_vigil.html">
            <div class="project">
                <h2 class="project-title"><b>Vigil</b></h2>
                <p>bee-hive health.</p><div class="badge closed-source">Closed Source</div> <div class="badge alpha">Alpha</div> <div class="badge active">Active</div> <div class="badge rust">Language: rust</div><div class="badge python">Language: python</div> <div class="badge framework">Tool: pytorch</div>
            </div>
        </a></td>`,`<td>
        <a href="project_steam.rs.html">
            <div class="project">
                <h2 class="project-title"><b>Steam.rs</b></h2>
                <p>Steamworks api in Rust-lang.</p><a class="badge open-source" href="https://github.com/garhow/steam-rs" target="_blank">Open Source</a> <div class="badge beta">Beta</div> <div class="badge active">Active</div> <div class="badge rust">Language: rust</div> 
            </div>
        </a></td>`,`<td>
        <a href="project_passenger.html">
            <div class="project">
                <h2 class="project-title"><b>Passenger</b></h2>
                <p>Machine Learning powered computer assistant.</p><div class="badge planned-open-source">Planned to be Open Source</div> <div class="badge stable">Stable</div> <div class="badge maintenance">In Maintenance</div> <div class="badge rust">Language: rust</div><div class="badge html">Language: html</div><div class="badge css">Language: css</div><div class="badge js">Language: js</div> <div class="badge framework">Framework: tauri</div><div class="badge ai">Ai: Miquliz</div><div class="badge framework">Tool: gpt-4</div>
            </div>
        </a></td>`,`<td>
        <a href="project_venture/navigator.html">
            <div class="project">
                <h2 class="project-title"><b>Venture/Navigator</b></h2>
                <p>Job search engine.</p><div class="badge planned-open-source">Planned to be Open Source</div> <div class="badge beta">Beta</div> <div class="badge active">Active</div> <div class="badge rust">Language: rust</div> 
            </div>
        </a></td>`,
]

export function addProject(width_selector) {

    var contain = document.querySelector('.card');

    var footer = document.querySelector('footer');
    var buffer = "";
    var loops = 0;

    for (;;) {
    
        if (loops > 5) {
            width_selector = 1;
        }
        console.log("Width: "+width_selector);
        buffer = '<table><tr>';
        for (let i = 0; i < PROJECTS.length; i++) {
            console.log(i % width_selector);
            console.log(i % width_selector === 0);

            if (i % width_selector === 0) {
                buffer += '</tr><tr>';
            }

            buffer += `${PROJECTS[i]}`;
        }

        buffer += '</tr></table>';
        contain.innerHTML = buffer;

        if (loops > 5) { break; }

        // var screenWidth = window.screen.width;
        console.log("Screen width: " + footer.scrollWidth, "Contain width: " + contain.clientWidth);

        if (contain.clientWidth > footer.scrollWidth-100) {
            console.log("Overflown");
            width_selector--;
        } else { break }

        loops++;
    }

}