[[project]]
name = "website"
description = "This website"
source_status = "open"
src = "https://github.com/marcohoovy/2024-website"
dev_status = "alpha"
maintenance = "active"
languages = [
    "js",
    "html",
    "css",
    "rust",
    "wasm",
]
tools = ["vite"]
epoch = 0
new = false

[[project]]
name = "olympus"
description = "Machine Learning powered stock trading algorithm"
source_status = "closed"
dev_status = "stable"
maintenance = "maintenance"
languages = ["rust"]
tools = ["pytorch"]
epoch = 0
new = false

[[project]]
name = "avaritia"
description = "Cryptocurrency trading bot"
source_status = "closed"
dev_status = "stable"
maintenance = "deprecated"
languages = ["rust"]
tools = []
epoch = 0
new = false

[[project]]
name = "vigil"
description = "bee-hive health"
source_status = "closed"
dev_status = "alpha"
maintenance = "active"
languages = [
    "rust",
    "python",
]
tools = ["pytorch"]
epoch = 0
new = false

[[project]]
name = "steam.rs"
description = "Steamworks api in Rust-lang"
source_status = "open"
src = "https://github.com/garhow/steam-rs"
dev_status = "beta"
maintenance = "active"
languages = ["rust"]
tools = []
epoch = 0
new = false

[[project]]
name = "passenger"
description = "Machine Learning powered computer assistant"
source_status = "planned"
dev_status = "stable"
maintenance = "maintenance"
languages = [
    "rust",
    "html",
    "css",
    "js",
]
tools = ["tauri"]
epoch = 0
new = false

[[project]]
name = "secret-santa"
description = "Web based Secret Santa used in 2023"
source_status = "planned"
dev_status = "stable"
maintenance = "deprecated"
languages = ["rust","html"]
tools = []
epoch = 0
new = false

[[project]]
name = "hoover api"
description = "The secret backend for this website"
source_status = "closed"
dev_status = "stable"
maintenance = "active"
languages = [
    "rust",
    "python",
]
tools = ["robyn"]
epoch = 0
new = false

[[project]]
name = "venture"
description = "Job search engine"
source_status = "closed"
dev_status = "stable"
maintenance = "deprecated"
languages = []
tools = []
epoch = 0
new = false

[[project]]
name = "aurpm"
description = "Arch User Repository Package Manager"
source_status = "open"
src = "https://github.com/marcohoovy/aurpm"
dev_status = "stable"
maintenance = "deprecated"
languages = [
    "rust",
    "python",
]
tools = []
epoch = 0
new = false

[[project]]
name = "rust.rs"
description = "Unofficial Rust+ for the desktop"
source_status = "closed"
dev_status = "beta"
maintenance = "deprecated"
languages = [
    "rust",
    "python",
]
tools = []
epoch = 0
new = false

[[project]]
name = "mpd mc"
description = "Music Player Daemon event based client for Minecraft"
source_status = "open"
src = "https://github.com/marcohoovy/mpd_controller"
dev_status = "stable"
maintenance = "maintenance"
languages = ["java"]
tools = []
epoch = 0
new = false

[[project]]
name = "league of music 2"
description = "League of Legeneds Compatible sound board"
source_status = "planned"
dev_status = "stable"
maintenance = "maintenance"
languages = ["rust"]
tools = ["slint"]
epoch = 0
new = false

[[project]]
name = "league of music"
description = "League of Legeneds Compatible sound board"
source_status = "open"
src = "https://github.com/marcohoovy/league-of-music.git"
dev_status = "stable"
maintenance = "deprecated"
languages = ["rust"]
tools = []
epoch = 1693315056
new = false

[[project]]
name = "ultrabot"
description = "Ultrakill Ai"
source_status = "closed"
dev_status = "alpha"
maintenance = "active"
languages = ["C#"]
tools = []
epoch = 0
new = false

[[project]]
name = "archivist"
description = "Project Sorter & Archiver"
source_status = "open"
src = "https://github.com/marcohoovy/archivist.git"
dev_status = "stable"
maintenance = "active"
languages = []
tools = []
epoch = 1713646185
new = true